export const publicRoutePaths = {
  dashboard: '/',
  leaderboard: '/leaderboard',
  players: '/players/:playerId',
  compare: '/compare',
  synergy: '/synergy',
  maps: '/maps',
  agents: '/agents',
  weapons: '/weapons',
  matches: '/matches',
  connect: '/connect',
  dictionary: '/dictionary',
  about: '/about',
  privacy: '/privacy',
} as const;
